version: '3'

volumes:
  pg_data_taski:
  static_volume_taski:

services:
  db:
    container_name: taski-db
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data_taski:/var/lib/postgresql/data

  backend:
    container_name: taski-backend
    image: andprov/taski_backend
    env_file: .env
    volumes:
      - static_volume_taski
    depends_on:
      - db

  frontend:
    container_name: taski-frontend
    image: andprov/taski_frontend
    env_file: .env
    command: cp -r /app/build/. /frontend_static
    volumes:
      - static_volume_taski

  gateway:
    container_name: taski-gateway
    image: andprov/taski_gateway
    env_file: .env
    volumes:
      - static_volume_taski
    ports:
      - 8000:80