version: '3'

volumes:
  pg_data:
  static:

services:
  db:
    container_name: taski-db
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    container_name: taski-backend
    image: andprov/taski_backend
    env_file: .env
    volumes:
      - static:/backend_static
    depends_on:
      - db

  frontend:
    container_name: taski-frontend
    image: andprov/taski_frontend
    env_file: .env
    volumes:
      - static:/frontend_static
    command: cp -r /app/build/. /frontend_static

  gateway:
    container_name: taski-gateway
    image: andprov/taski_gateway
    env_file: .env
    volumes:
      - static:/staticfiles
    ports:
      - 8000:80