version: '3'

volumes:
  pg_data_taski:
  static_volume_taski:

services:
  db:
    container_name: taski-db
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data_taski:/var/lib/postgresql/data

  backend:
    container_name: taski-backend
    build: ./backend
    env_file: .env
    volumes:
      - static_volume_taski:/backend_static
    depends_on:
      - db

  frontend:
    container_name: taski-frontend
    env_file: .env
    build: ./frontend
    volumes:
      - static_volume_taski:/frontend_static
    command: cp -r /app/build/. /frontend_static

  gateway:
    container_name: taski-gateway
    build: ./gateway
    env_file: .env
    volumes:
      - static_volume_taski:/staticfiles
    ports:
      - 8000:80